<div><p class="eyebrow">Codenyr / Gestion commerciale</p><div class="admin-toolbar"><h1>{{ $title }}</h1>@if($module!=='settings')<button class="button button-primary" wire:click="create">+ Ajouter</button>@endif</div>
@if($module==='catalog')<p>Les offres liées aux tarifs publics utilisent les mêmes prix que la page Tarifs. Les prestations ajoutées sont indépendantes.</p>@elseif($module==='templates')<p>Rédigez vos textes validés. Variables disponibles : <code>@{{client}}</code>, <code>@{{project}}</code>, <code>@{{seller}}</code>, <code>@{{amount}}</code>, <code>@{{delay}}</code>, <code>@{{services}}</code>, <code>@{{payment}}</code>. Chaque document généré conserve une copie du texte utilisé.</p>@elseif($module==='settings')<p>Complétez l’identité de l’entreprise et les mentions applicables avant d’émettre des documents définitifs.</p>@endif
@include('livewire.admin.commercial-errors')
@if($showForm)<section class="admin-panel"><h2>{{ $module==='settings' ? 'Configuration' : ($editing ? 'Modifier' : 'Ajouter') }}</h2><form wire:submit="save"><div class="form-grid">
@php($labels = match($module) { 'clients'=>['name'=>'Entreprise / nom','contact'=>'Contact','email'=>'E-mail','phone'=>'Téléphone','address'=>'Adresse','registration'=>'SIRET / identifiant'], 'catalog'=>['category'=>'Catégorie','name'=>'Nom','description'=>'Description','price'=>'Prix HT (€)','unit'=>'Unité','position'=>'Ordre d’affichage'], 'templates'=>['name'=>'Nom du modèle','content'=>'Texte du modèle'], default=>['name'=>'Nom commercial','legal_name'=>'Raison sociale','address'=>'Adresse','phone'=>'Téléphone','email'=>'E-mail','registration'=>'SIRET','vat_rate'=>'Taux de TVA (%)','tax_mention'=>'Mention fiscale','quote_prefix'=>'Préfixe devis','invoice_prefix'=>'Préfixe factures','validity_days'=>'Validité des devis (jours)','payment_days'=>'Délai de paiement (jours)','deposit_percent'=>'Acompte par défaut (%)','quote_followup_days'=>'Alerte devis sans réponse (jours)','delivery_alert_days'=>'Alerte livraison proche (jours)','quote_mention'=>'Conditions des devis','invoice_mention'=>'Mentions des factures','footer'=>'Pied de page'] })
@foreach($labels as $key=>$label)<div @class(['field','full'=>in_array($key,['content','description','quote_mention','invoice_mention'])])><label for="directory-{{ $key }}">{{ $label }}</label>@if(in_array($key,['address','description','content','tax_mention','quote_mention','invoice_mention','footer']))<textarea id="directory-{{ $key }}" wire:model="form.{{ $key }}" rows="{{ $key==='content' ? 15 : 3 }}"></textarea>@else<input id="directory-{{ $key }}" wire:model="form.{{ $key }}" type="{{ $key==='email' ? 'email' : 'text' }}">@endif</div>@endforeach
@if($module==='catalog')<div class="field"><label for="service-frequency">Fréquence</label><select id="service-frequency" wire:model="form.frequency">@foreach(\App\Models\Service::FREQUENCIES as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div><label class="commercial-checkbox"><input type="checkbox" wire:model="form.active"> Prestation active</label>@endif
@if($module==='templates')<div class="field"><label for="template-type">Type</label><select id="template-type" wire:model="form.type">@foreach(['terms','contract','maintenance','legal','commercial','other'] as $key)<option value="{{ $key }}">{{ \App\Models\Document::TYPES[$key] }}</option>@endforeach</select></div>@endif
@if($module==='settings')<label class="commercial-checkbox"><input type="checkbox" wire:model="form.vat_enabled"> TVA activée</label><div class="field"><label for="commercial-logo">Logo des futurs documents (PNG / JPEG, 2 Mo maximum)</label><input id="commercial-logo" type="file" accept=".png,.jpg,.jpeg" wire:model="logo"><small>Sans fichier, le logo Codenyr existant est conservé. Les anciens documents gardent leur logo.</small></div>@endif
</div><div class="button-row"><button class="button button-primary" wire:loading.attr="disabled">Enregistrer</button>@if($module!=='settings')<button class="button button-secondary" type="button" wire:click="$set('showForm',false)">Annuler</button>@endif</div></form></section>@endif
@if($module!=='settings')<div class="admin-toolbar"><input aria-label="Rechercher" placeholder="Rechercher…" wire:model.live.debounce.300ms="search"></div><section class="admin-panel table-wrap"><table class="admin-table"><thead><tr><th>Nom</th><th>Informations</th><th></th></tr></thead><tbody>@forelse($records as $record)<tr><td><strong>{{ $record->name }}</strong></td><td>@if($module==='clients'){{ $record->email }}<small>{{ $record->contact }} · {{ $record->phone }}</small><a class="text-link" href="{{ route('admin.client-projects.index',['search'=>$record->name]) }}">Projets du client</a>@elseif($module==='catalog'){{ $record->category }} · {{ \App\Services\CommercialCalculator::euros($record->currentPrice()) }}<small>{{ \App\Models\Service::FREQUENCIES[$record->frequency] }} · {{ $record->active ? 'Active' : 'Inactive' }} {{ $record->price_key ? '· Liée aux tarifs publics' : '' }}</small>@else{{ \App\Models\Document::TYPES[$record->type] }} · version {{ $record->revision }}@endif</td><td><button class="text-link" wire:click="edit({{ $record->id }})">Modifier</button></td></tr>@empty<tr><td colspan="3">Aucun élément.</td></tr>@endforelse</tbody></table></section>@endif
</div>
