<div><p class="eyebrow">Codenyr / Gestion commerciale</p><div class="admin-toolbar"><h1>Documents</h1><div class="button-row"><a class="button button-secondary" href="{{ route('admin.document-templates') }}">Modèles de textes</a><button class="button button-primary" wire:click="create">+ Ajouter / importer</button></div></div>@include('livewire.admin.commercial-errors')
@if($showForm)<section class="admin-panel"><div class="admin-toolbar"><h2>{{ !empty($form['original_id']) ? 'Importer une version signée' : 'Ajouter un document' }}</h2><button class="button button-secondary" wire:click="$set('showForm',false)">Fermer</button></div><form wire:submit="save"><div class="form-grid">
<div class="field"><label for="document-mode">Source</label><select id="document-mode" wire:model.live="mode"><option value="upload">Importer un fichier</option><option value="generate">Créer depuis un texte / modèle</option></select></div>
<div class="field"><label for="document-name">Nom</label><input id="document-name" wire:model="form.name"></div>
<div class="field"><label for="document-type">Type</label><select id="document-type" wire:model="form.type">@foreach(\App\Models\Document::TYPES as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div>
<div class="field"><label for="document-project">Projet</label><select id="document-project" wire:model.live="form.client_project_id"><option value="">Sans projet</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->name }} — {{ $project->client->name }}{{ $project->archived_at ? ' (archivé)' : '' }}</option>@endforeach</select></div>
<div class="field"><label for="document-client">Client (automatique si projet sélectionné)</label><select id="document-client" wire:model="form.client_id"><option value="">Client du projet</option>@foreach($clients as $client)<option value="{{ $client->id }}">{{ $client->name }}</option>@endforeach</select></div>
<div class="field"><label for="document-date">Date</label><input id="document-date" type="date" wire:model="form.document_date"></div>
<div class="field"><label for="document-quote">Devis associé (facultatif)</label><select id="document-quote" wire:model="form.quote_id"><option value="">Aucun</option>@foreach($quotes as $quote)@if((int)($form['client_project_id']??0)===$quote->client_project_id)<option value="{{ $quote->id }}">{{ $quote->number }}</option>@endif @endforeach</select></div>
<div class="field"><label for="document-invoice">Facture associée (facultatif)</label><select id="document-invoice" wire:model="form.invoice_id"><option value="">Aucune</option>@foreach($invoices as $invoice)@if((int)($form['client_project_id']??0)===$invoice->client_project_id)<option value="{{ $invoice->id }}">{{ $invoice->number }}</option>@endif @endforeach</select></div>
@foreach(['description'=>'Description','notes'=>'Notes internes'] as $key=>$label)<div class="field"><label for="document-{{ $key }}">{{ $label }}</label><textarea id="document-{{ $key }}" wire:model="form.{{ $key }}" rows="2"></textarea></div>@endforeach
@if($mode==='upload')<div class="field full"><label for="document-upload">Fichier — PDF, DOCX, XLSX, PNG, JPEG · maximum 20 Mo</label><input id="document-upload" type="file" accept=".pdf,.docx,.xlsx,.png,.jpg,.jpeg" wire:model="upload"><span wire:loading wire:target="upload">Transfert du fichier…</span></div>@else<div class="field full"><label for="document-template">Modèle de texte</label><select id="document-template" wire:model.live="form.template_id"><option value="">Texte libre</option>@foreach($templates as $template)<option value="{{ $template->id }}">{{ $template->name }} — v{{ $template->revision }}</option>@endforeach</select></div><div class="field full"><label for="document-content">Texte (copie conservée pour ce document)</label><textarea id="document-content" wire:model.live.debounce.500ms="form.content" rows="16"></textarea></div>@endif
</div><button class="button button-primary" wire:loading.attr="disabled">Enregistrer le document</button></form>@if($mode==='generate' && !empty($form['content']))<details><summary>Aperçu du texte avant remplacement des variables</summary><p class="preserve-lines">{{ $form['content'] }}</p></details>@endif</section>@endif
@if($preview)<section class="admin-panel"><div class="admin-toolbar"><h2>{{ $preview->name }}</h2><button class="button button-secondary" wire:click="$set('previewId',null)">Fermer l’aperçu</button></div><p>{{ $preview->description }}</p><p class="preserve-lines">{{ $preview->content }}</p><p class="preserve-lines">{{ $preview->notes }}</p>@if($preview->path)@if($preview->mime === 'application/pdf')<iframe class="commercial-document-preview" title="Aperçu du document PDF" src="{{ route('admin.documents.show',$preview) }}"></iframe>@elseif(in_array($preview->mime,['image/png','image/jpeg']))<img class="commercial-image-preview" alt="{{ $preview->name }}" src="{{ route('admin.documents.show',$preview) }}">@endif<a class="button button-primary" href="{{ route('admin.documents.download',$preview) }}">Télécharger</a>@elseif($preview->content)<button class="button button-primary" wire:click="generate({{ $preview->id }})">Générer et télécharger le PDF</button>@endif @if($preview->versions->count()>1)<h3>Versions conservées</h3>@foreach($preview->versions as $version)<p><a class="text-link" href="{{ route('admin.documents.version',$version) }}">Version {{ $version->version }} — {{ $version->created_at->format('d/m/Y H:i') }}</a></p>@endforeach @endif</section>@endif
<div class="admin-panel"><div class="form-grid"><div class="field"><label for="doc-search">Recherche</label><input id="doc-search" wire:model.live.debounce.300ms="search" placeholder="Nom, numéro, client ou projet…"></div><div class="field"><label for="doc-project-filter">Projet</label><select id="doc-project-filter" wire:model.live="projectFilter"><option value="">Tous</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->name }}</option>@endforeach</select></div><div class="field"><label for="doc-client-filter">Client</label><select id="doc-client-filter" wire:model.live="clientFilter"><option value="">Tous</option>@foreach($clients as $client)<option value="{{ $client->id }}">{{ $client->name }}</option>@endforeach</select></div><div class="field"><label for="doc-type-filter">Type</label><select id="doc-type-filter" wire:model.live="typeFilter"><option value="">Tous</option>@foreach(\App\Models\Document::TYPES as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div><div class="field"><label for="doc-year">Année</label><input id="doc-year" wire:model.live.debounce.400ms="yearFilter" placeholder="2026" inputmode="numeric"></div><div class="field"><label for="doc-date-filter">Date</label><input id="doc-date-filter" type="date" wire:model.live="dateFilter"></div><div class="field"><label for="doc-status-filter">Statut</label><select id="doc-status-filter" wire:model.live="statusFilter"><option value="">Disponibles</option><option value="signed">Versions signées</option><option value="archived">Archivés</option></select></div></div></div>
<div class="admin-panel table-wrap">@include('livewire.admin.document-table')</div>{{ $documents->links() }}</div>

