<div>
    <p class="eyebrow"><a href="{{ route('admin.client-projects.index') }}">Projets</a> / {{ $project->client->name }}</p>
    <div class="admin-toolbar"><div><h1>{{ $project->name }}</h1><p>{{ $project->client->name }} · <span class="status-pill">{{ $project->archived_at ? 'Archivé' : \App\Models\ClientProject::STATUSES[$project->status] }}</span></p></div><div class="button-row">@unless($project->archived_at)<button class="button button-secondary" wire:click="edit">Modifier le projet</button>@endunless<button class="button button-secondary" wire:click="archive" wire:confirm="{{ $project->archived_at ? 'Restaurer ce dossier ?' : 'Archiver ce dossier ? Il restera consultable.' }}">{{ $project->archived_at ? 'Restaurer' : 'Archiver' }}</button></div></div>
    @include('livewire.admin.commercial-errors')
    <details class="admin-panel">
        <summary>Client et accès à l’espace client</summary>
        <p>Client : <strong>{{ $project->client->name }}</strong> · Compte associé : <strong>{{ $project->user?->email ?? 'Aucun compte' }}</strong></p>
        <form wire:submit="saveAccess">
            <div class="form-grid">
                <div class="field"><label for="project-client">Client du projet</label><select id="project-client" wire:model.live="accessClientId">
                    @foreach($clients as $client)
                        <option value="{{ $client->id }}">{{ $client->name }} — {{ $client->email }}</option>
                    @endforeach
                </select></div>
                <div class="field"><label for="project-account">E-mail du compte client (facultatif)</label><input id="project-account" type="email" wire:model="accountEmail" placeholder="Adresse utilisée pour se connecter"></div>
            </div>
            <p>Le client peut <a class="text-link" href="{{ route('register') }}" target="_blank" rel="noopener">créer son compte</a>, puis vous pouvez le rattacher ici. Laissez l’e-mail vide pour retirer l’accès.</p>
            <p>Changer le client ou le compte retire l’ancien accès et masque les documents jusqu’à un nouveau partage. Les devis et factures déjà enregistrés conservent leurs coordonnées historiques. Les nouveaux documents utilisent le client choisi.</p>
            <button class="button button-primary" wire:loading.attr="disabled">Enregistrer le client et l’accès</button>
        </form>
    </details>
    @if($editing)<section class="admin-panel"><h2>Modifier le projet</h2><form wire:submit="save"><div class="form-grid">@include('livewire.admin.project-fields')</div><div class="button-row"><button class="button button-primary">Enregistrer</button><button type="button" class="button button-secondary" wire:click="$set('editing', false)">Annuler</button></div></form></section>@endif
    <div class="admin-stats commercial-stats">
        <div class="stat-card"><span>Facturé</span><strong>{{ \App\Services\CommercialCalculator::euros($billed) }}</strong><small>Factures émises</small></div>
        <div class="stat-card"><span>Payé</span><strong>{{ \App\Services\CommercialCalculator::euros($paid) }}</strong><small>Paiements enregistrés</small></div>
        <div class="stat-card"><span>Reste dû</span><strong>{{ \App\Services\CommercialCalculator::euros($billed - $paid) }}</strong><small>Sur factures émises</small></div>
        <div class="stat-card"><span>Documents</span><strong>{{ $project->documents->where('type','!=','work')->count() }}</strong></div>
        <div class="stat-card"><span>Livraison prévue</span><strong>{{ $project->due_on?->format('d/m/Y') ?? 'À définir' }}</strong></div>
    </div>
    @unless($project->archived_at)<div class="button-row commercial-actions"><a class="button button-primary" href="{{ route('admin.billing.create', ['kind'=>'quotes', 'project'=>$project->id]) }}">+ Créer un devis</a><a class="button button-secondary" href="{{ route('admin.billing.create', ['kind'=>'invoices', 'project'=>$project->id]) }}">Créer une facture</a><a class="button button-secondary" href="{{ route('admin.documents', ['project'=>$project->id, 'create'=>1]) }}">Ajouter / importer un document</a><button class="button button-secondary" wire:click="$set('tab','notes')">Ajouter une note</button></div>@endunless
    @unless($project->archived_at)<div class="button-row commercial-actions">@foreach(['terms'=>'Créer les CGV','contract'=>'Créer le contrat de prestation'] as $kind=>$label)<a class="button button-secondary" href="{{ route('admin.documents',['project'=>$project->id,'create'=>1,'type'=>$kind,'mode'=>'generate']) }}">{{ $label }}</a>@endforeach</div>@endunless
    @if($previewDocumentId)<section class="admin-panel"><div class="admin-toolbar"><h2>Aperçu du PDF</h2><button class="button button-secondary" wire:click="$set('previewDocumentId',null)">Fermer l’aperçu</button></div><iframe class="commercial-document-preview" title="Aperçu du PDF du projet" src="{{ route('admin.documents.show',$previewDocumentId) }}"></iframe></section>@endif
    <nav class="commercial-tabs" aria-label="Dossier projet">@foreach(['summary'=>'Résumé','quotes'=>'Devis','invoices'=>'Factures','payments'=>'Paiements','documents'=>'Documents','contracts'=>'Contrats','maintenance'=>'Maintenance','files'=>'Fichiers','notes'=>'Notes','history'=>'Historique'] as $key=>$label)<button type="button" wire:click="$set('tab','{{ $key }}')" @class(['active'=>$tab===$key]) aria-current="{{ $tab===$key ? 'page' : 'false' }}">{{ $label }}</button>@endforeach</nav>
    @unless($project->archived_at)<details class="admin-panel"><summary>+ Ajouter au dossier</summary><div class="button-row commercial-actions"><a class="button button-secondary" href="{{ route('admin.billing.create',['kind'=>'quotes','project'=>$project->id]) }}">Devis</a><a class="button button-secondary" href="{{ route('admin.billing.create',['kind'=>'invoices','project'=>$project->id]) }}">Facture</a><button class="button button-secondary" wire:click="$set('tab','payments')">Paiement</button>@foreach(['terms'=>'CGV','contract'=>'Contrat de prestation','work'=>'Fichier de travail','other'=>'Document'] as $key=>$label)<a class="button button-secondary" href="{{ route('admin.documents',['project'=>$project->id,'create'=>1,'type'=>$key,'mode'=>in_array($key,['terms','contract']) ? 'generate' : 'upload']) }}">{{ $label }}</a>@endforeach<button class="button button-secondary" wire:click="$set('tab','maintenance')">Maintenance</button><button class="button button-secondary" wire:click="$set('tab','notes')">Note</button></div></details>@endunless
    @if($tab==='summary')
        <section class="admin-panel"><div class="admin-toolbar"><h2>Devis du projet</h2><button class="text-link" wire:click="$set('tab','quotes')">Gérer les devis →</button></div>@forelse($project->quotes->sortByDesc('id') as $quote)<p><a class="text-link" href="{{ route('admin.billing.edit',['kind'=>'quotes','id'=>$quote->id]) }}">{{ $quote->number }}</a> · {{ \App\Services\CommercialCalculator::euros($quote->totals['initial']['ttc']) }} TTC initial · {{ \App\Models\Quote::STATUSES[$quote->status] }}@if($quote->status==='accepted')<br><small>Reste à facturer sur ce devis : {{ \App\Services\CommercialCalculator::euros(max(0,$quote->totals['initial']['ttc'] - $project->invoices->where('quote_id',$quote->id)->whereNotNull('finalized_at')->sum(fn($i)=>$i->totals['initial']['ttc']))) }}</small>@endif</p>@empty<p>À préparer.</p>@endforelse</section>
        <div class="commercial-columns"><section class="admin-panel"><h2>Client et projet</h2><p><strong>{{ $project->client->name }}</strong><br>{{ $project->client->contact }}<br>{{ $project->client->email }}<br>{{ $project->client->phone }}</p><p class="preserve-lines">{{ $project->client->address }}</p><p>{{ $project->type }} · Début {{ $project->starts_on?->format('d/m/Y') ?? 'à définir' }}</p><p class="preserve-lines">{{ $project->description }}</p>@if($project->website_url)<a href="{{ $project->website_url }}" target="_blank" rel="noopener" class="text-link">Voir le site ↗</a>@endif<p>{{ $project->domain }} {{ $project->host }}</p><p class="preserve-lines">{{ $project->internal_notes }}</p>@if($project->lead_id)<p>Prospect d’origine #{{ $project->lead_id }} · Les droits d’avis restent gérés dans <a class="text-link" href="{{ route('admin.leads') }}">Prospects</a>.</p>@endif</section>
        <section class="admin-panel"><h2>Dossier administratif : {{ (int) round(count(array_filter($checklist))/max(1,count($checklist))*100) }} %</h2><progress max="{{ count($checklist) }}" value="{{ count(array_filter($checklist)) }}"></progress><ul class="commercial-checklist">@foreach($checklist as $label=>$present)<li><span aria-label="{{ $present ? 'Présent' : 'À compléter' }}">{{ $present ? '✓' : '○' }}</span> {{ $label }}</li>@endforeach</ul><small>Progression documentaire, indépendante du développement.</small></section></div>
        @if(count($alerts))<section class="admin-panel"><h2>Actions requises</h2><ul class="commercial-checklist">@foreach($alerts as $alert)<li>{{ $alert }}</li>@endforeach</ul></section>@endif
        <section class="admin-panel"><h2>Maintenance</h2>@forelse($project->maintenance as $maintenance)<p>{{ $maintenance->name }} · {{ \App\Services\CommercialCalculator::euros($maintenance->amount_cents) }} / {{ \App\Models\Service::FREQUENCIES[$maintenance->frequency] }} · {{ \App\Models\MaintenanceContract::STATUSES[$maintenance->status] }}</p>@empty<p>Non définie.</p>@endforelse</section>
    @elseif(in_array($tab,['quotes','invoices']))
        <div class="admin-panel table-wrap"><table class="admin-table"><thead><tr><th>Numéro</th><th>Total initial TTC</th><th>Statut</th><th>Échéance</th><th>Actions</th></tr></thead><tbody>@forelse($tab==='quotes' ? $project->quotes : $project->invoices as $record)<tr><td>{{ $record->number ?? 'Brouillon #'.$record->id }}</td><td>{{ \App\Services\CommercialCalculator::euros($record->totals['initial']['ttc']) }}@foreach($record->totals['recurring'] as $frequency=>$total)@if($total['ttc'])<small>{{ \App\Services\CommercialCalculator::euros($total['ttc']) }} / {{ \App\Models\Service::FREQUENCIES[$frequency] }}</small>@endif @endforeach</td><td>{{ $record->archived_at ? 'Archivé' : ($tab==='quotes' ? \App\Models\Quote::STATUSES[$record->status] : $record->paymentLabel()) }}</td><td>{{ $record->due_on->format('d/m/Y') }}</td><td><a class="text-link" href="{{ route('admin.billing.edit',['kind'=>$tab,'id'=>$record->id]) }}">Consulter</a>@if($tab==='quotes' && $record->status==='accepted' && !$project->archived_at)<div class="button-row"><button class="button button-secondary" wire:click="invoiceFromQuote({{ $record->id }}, 'deposit')">Facturer l’acompte</button><button class="button button-secondary" wire:click="invoiceFromQuote({{ $record->id }}, 'balance')">Facturer le solde</button></div>@endif</td></tr>@empty<tr><td colspan="5">Aucun document.</td></tr>@endforelse</tbody></table></div>
    @elseif($tab==='payments')
        @unless($project->archived_at)<section class="admin-panel"><h2>Enregistrer un paiement</h2><form wire:submit="pay"><div class="form-grid"><div class="field"><label for="payment-invoice">Facture émise</label><select id="payment-invoice" wire:model="payment.invoice_id"><option value="">Choisir une facture</option>@foreach($project->invoices->whereNotNull('finalized_at') as $invoice)<option value="{{ $invoice->id }}">{{ $invoice->number }} — reste {{ \App\Services\CommercialCalculator::euros($invoice->remainingCents()) }}</option>@endforeach</select></div><div class="field"><label for="payment-method">Moyen</label><select id="payment-method" wire:model="payment.method">@foreach(\App\Models\Payment::METHODS as $key=>$label)<option value="{{ $key }}">{{ $label }}</option>@endforeach</select></div>@foreach(['amount'=>'Montant (€)','paid_on'=>'Date','reference'=>'Référence','comment'=>'Commentaire'] as $key=>$label)<div class="field"><label for="payment-{{ $key }}">{{ $label }}</label><input id="payment-{{ $key }}" wire:model="payment.{{ $key }}" type="{{ $key==='paid_on' ? 'date' : 'text' }}"></div>@endforeach</div><button class="button button-primary" wire:loading.attr="disabled">Enregistrer le paiement</button></form></section>@endunless
        <div class="admin-panel table-wrap"><table class="admin-table"><thead><tr><th>Date</th><th>Facture</th><th>Montant</th><th>Moyen / référence</th></tr></thead><tbody>@foreach($project->invoices as $invoice)@foreach($invoice->payments as $payment)<tr><td>{{ $payment->paid_on->format('d/m/Y') }}</td><td>{{ $invoice->number }}</td><td>{{ \App\Services\CommercialCalculator::euros($payment->amount_cents) }}</td><td>{{ \App\Models\Payment::METHODS[$payment->method] }}<small>{{ $payment->reference }} {{ $payment->comment }}@if($payment->voided_at) · Saisie annulée : {{ $payment->void_reason }}@endif</small></td></tr>@endforeach @endforeach</tbody></table></div>
    @elseif(in_array($tab,['documents','contracts','files']))
        <section class="admin-panel"><div class="admin-toolbar"><h2>{{ $tab==='files' ? 'Fichiers de travail' : 'Documents du dossier' }}</h2><a class="text-link" href="{{ route('admin.documents',['project'=>$project->id]) }}">Gérer les documents →</a></div>@php($documents = $project->documents->filter(fn($d) => $tab==='files' ? $d->type==='work' : ($tab==='contracts' ? in_array($d->type,['contract','maintenance','terms']) : $d->type!=='work')))<div class="table-wrap">@include('livewire.admin.document-table')</div></section>
    @elseif($tab==='notes')
        @unless($project->archived_at)<section class="admin-panel"><h2>Ajouter une note</h2><form wire:submit="addNote"><div class="field"><label for="project-note">Note interne</label><textarea id="project-note" rows="4" wire:model="note"></textarea></div><label class="commercial-checkbox"><input type="checkbox" wire:model="pinned"> Épingler</label><button class="button button-primary">Ajouter la note</button></form></section>@endunless
        @forelse($project->notes->sortByDesc('created_at')->sortByDesc('pinned') as $note)<article class="admin-panel"><p class="preserve-lines">{{ $note->content }}</p><small>{{ $note->author?->name ?? 'Ancien administrateur' }} · {{ $note->created_at->format('d/m/Y H:i') }} {{ $note->pinned ? '· Épinglée' : '' }}</small>@unless($project->archived_at)<button class="text-link" wire:click="pinNote({{ $note->id }})">{{ $note->pinned ? 'Désépingler' : 'Épingler' }}</button>@endunless</article>@empty<p>Aucune note.</p>@endforelse
    @elseif($tab==='history')
        <section class="admin-panel"><h2>Historique</h2><ol class="commercial-timeline">@foreach($project->events->sortByDesc('id') as $event)<li><time>{{ $event->created_at->format('d/m/Y H:i') }}</time><p>{{ $event->description }}</p></li>@endforeach</ol></section>
    @elseif($tab==='maintenance')
        @unless($project->archived_at)<section class="admin-panel"><h2>Préparer une maintenance</h2><form wire:submit="addMaintenance"><div class="form-grid">@foreach(['name'=>'Nom','amount'=>'Montant (€)','starts_on'=>'Début','duration_months'=>'Durée (mois)','renewal'=>'Renouvellement','included'=>'Prestations incluses','response_time'=>'Délai d’intervention','termination'=>'Résiliation','notes'=>'Notes'] as $key=>$label)<div class="field"><label for="maintenance-{{ $key }}">{{ $label }}</label><input id="maintenance-{{ $key }}" wire:model="maintenanceForm.{{ $key }}" type="{{ $key==='starts_on' ? 'date' : 'text' }}"></div>@endforeach<div class="field"><label for="maintenance-frequency">Fréquence</label><select id="maintenance-frequency" wire:model="maintenanceForm.frequency">@foreach(['monthly','quarterly','yearly'] as $frequency)<option value="{{ $frequency }}">{{ \App\Models\Service::FREQUENCIES[$frequency] }}</option>@endforeach</select></div></div><button class="button button-primary">Ajouter la maintenance</button></form></section>@endunless
        @foreach($project->maintenance as $maintenance)<section class="admin-panel"><h2>{{ $maintenance->name }}</h2><p>{{ \App\Services\CommercialCalculator::euros($maintenance->amount_cents) }} / {{ \App\Models\Service::FREQUENCIES[$maintenance->frequency] }} · {{ \App\Models\MaintenanceContract::STATUSES[$maintenance->status] }}</p><p>{{ $maintenance->starts_on->format('d/m/Y') }} · {{ $maintenance->duration_months }} mois · {{ $maintenance->renewal }}</p><p class="preserve-lines">{{ $maintenance->included }}</p><p>Intervention : {{ $maintenance->response_time }} · Résiliation : {{ $maintenance->termination }}</p>@unless($project->archived_at)<div class="button-row">@foreach(['active'=>'Activer','suspended'=>'Suspendre','terminated'=>'Résilier','archived'=>'Archiver'] as $key=>$label)<button class="button button-secondary" wire:click="maintenanceStatus({{ $maintenance->id }},'{{ $key }}')" wire:confirm="{{ $label }} cette maintenance ?">{{ $label }}</button>@endforeach<a class="button button-primary" href="{{ route('admin.documents',['project'=>$project->id,'maintenance'=>$maintenance->id,'create'=>1]) }}">Générer le contrat</a></div>@endunless</section>@endforeach
    @endif
</div>
