<div><p class="eyebrow">Portfolio / Codenyr</p><h1>Réalisations</h1>@if(session('success'))<div class="flash" role="status">{{ session('success') }}</div>@endif<div class="admin-toolbar"><input wire:model.live.debounce.300ms="search" placeholder="Rechercher une réalisation…" aria-label="Rechercher une réalisation"><button class="button button-primary" wire:click="create">Nouvelle réalisation +</button></div>
@if($showForm)<form class="admin-panel" wire:submit="save"><h2>{{ $editing ? 'Modifier la réalisation' : 'Nouvelle réalisation' }}</h2>@if($errors->any())<div class="form-alert" role="alert">Vérifiez les champs du formulaire.</div>@endif<div class="form-grid">
@foreach(['name'=>'Nom *','slug'=>'Slug (généré si vide)','client'=>'Client *','category'=>'Secteur *','website_url'=>'URL du site (facultatif)','technologies'=>'Technologies séparées par des virgules'] as $field=>$label)<div class="field"><label for="project-{{ $field }}">{{ $label }}</label><input id="project-{{ $field }}" wire:model="form.{{ $field }}" type="{{ $field === 'website_url' ? 'url' : 'text' }}">@error('form.'.$field)<span class="error">{{ $message }}</span>@enderror</div>@endforeach
@foreach(['short_description'=>'Présentation courte *','description'=>'Description *','problem'=>'Problématique *','solution'=>'Solution Codenyr *','features'=>'Fonctionnalités'] as $field=>$label)<div class="field full"><label for="project-{{ $field }}">{{ $label }}</label><textarea id="project-{{ $field }}" wire:model="form.{{ $field }}" rows="3"></textarea>@error('form.'.$field)<span class="error">{{ $message }}</span>@enderror</div>@endforeach
<div class="field"><label for="project-image">Image principale (JPEG, PNG, WebP, AVIF · 4 Mo max.)</label><input id="project-image" type="file" wire:model="image" accept="image/jpeg,image/png,image/webp,image/avif">@error('image')<span class="error">{{ $message }}</span>@enderror @if($currentProject?->image)<img src="{{ $currentProject->imageUrl() }}" alt="Image actuelle" style="max-height:130px;object-fit:contain"><button type="button" class="text-link" wire:click="removeImage" wire:confirm="Supprimer l’image principale ?">Supprimer l’image actuelle</button>@endif</div>
<div class="field"><label for="project-screenshots">Galerie (6 images max., 4 Mo chacune ; remplace la galerie)</label><input id="project-screenshots" type="file" wire:model="screenshots" multiple accept="image/jpeg,image/png,image/webp,image/avif">@error('screenshots')<span class="error">{{ $message }}</span>@enderror @error('screenshots.*')<span class="error">{{ $message }}</span>@enderror @if($currentProject?->screenshots)<p>{{ count($currentProject->screenshots) }} capture(s) enregistrée(s).</p><button class="text-link" type="button" wire:click="removeScreenshots" wire:confirm="Supprimer toute la galerie ?">Supprimer la galerie</button>@endif</div>
@foreach(['published'=>'Publié sur le site','featured'=>'Mis en avant','is_demo'=>'Concept de démonstration (pas un projet client)'] as $field=>$label)<label class="inline-check"><input type="checkbox" wire:model="form.{{ $field }}">{{ $label }}</label>@error('form.'.$field)<span class="error">{{ $message }}</span>@enderror @endforeach
</div><div class="button-row"><button class="button button-primary" wire:loading.attr="disabled">Enregistrer</button><button type="button" class="button button-secondary" wire:click="$set('showForm', false)">Annuler</button><span wire:loading wire:target="image,screenshots">Téléversement en cours…</span></div></form>@endif
<div class="admin-panel table-wrap"><table class="admin-table"><thead><tr><th>Projet</th><th>Secteur</th><th>Publication</th><th>Actions</th></tr></thead><tbody>@forelse($projects as $project)<tr wire:key="project-{{ $project->id }}"><td>{{ $project->name }}<small>{{ $project->client }}</small></td><td>{{ $project->category }}</td><td>{{ $project->published ? 'Publié' : 'Brouillon' }}{{ $project->featured ? ' · À la une' : '' }}</td><td><button wire:click="edit({{ $project->id }})">Modifier</button><button class="danger" wire:click="delete({{ $project->id }})" wire:confirm="Supprimer cette réalisation et ses images ?">Supprimer</button></td></tr>@empty<tr><td colspan="4">Aucune réalisation.</td></tr>@endforelse</tbody></table></div><div class="admin-pagination">{{ $projects->links() }}</div></div>
