@php
    $pages = ['accueil' => 'Accueil', 'atelier' => 'L’atelier', 'expertises' => 'Expertises', 'realisations' => 'Réalisations', 'contact' => 'Contact'];
    $projects = [['Maison Lumière', 'Habitat', 'interieur.jpg', 'Des volumes ouverts, des teintes minérales et une lumière qui accompagne les heures.'], ['La Parenthèse', 'Rénovation', 'maison.jpg', 'Repenser les circulations et révéler le caractère d’un intérieur.'], ['Épure', 'Aménagement', 'matiere.jpg', 'Le bois, la pierre et des lignes simples composent un lieu apaisé.']];
    $settings = ['palette' => ['Palette', ['mineral' => 'Minéral & argile', 'olive' => 'Olive & lin', 'blue' => 'Bleu architectural', 'rose' => 'Rose poudré', 'dark' => 'Obsidienne']], 'type' => ['Typographie', ['signature' => 'Signature éditoriale', 'modern' => 'Contemporaine', 'classic' => 'Classique']], 'layout' => ['Présentation d’accueil', ['split' => 'Composition en deux colonnes', 'reverse' => 'Image à gauche', 'wide' => 'Panorama']], 'nav' => ['Navigation', ['standard' => 'Horizontale', 'center' => 'Centrée', 'sticky' => 'Fixe au défilement']], 'cards' => ['Présentation des projets', ['grid' => 'Grille', 'list' => 'Liste éditoriale']], 'corners' => ['Formes', ['square' => 'Angles droits', 'rounded' => 'Arrondis']], 'density' => ['Espacement', ['airy' => 'Généreux', 'compact' => 'Compact']], 'width' => ['Largeur du contenu', ['large' => 'Large', 'narrow' => 'Resserrée']], 'photos' => ['Traitement des photos', ['natural' => 'Naturel', 'mono' => 'Noir et blanc', 'warm' => 'Chaleureux']], 'buttons' => ['Style des boutons', ['solid' => 'Pleins', 'outline' => 'Contours']]];
@endphp
<!DOCTYPE html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>{{ $pages[$page] }} — Atelier Rive · Démonstration Codenyr</title>@fonts @vite('resources/js/demo-vitrine.js')</head><body>
<a class="skip" href="#main">Aller au contenu</a>
<div class="demo-banner"><span>ATELIER RIVE · Concept fictif par Codenyr</span><a href="{{ route('services') }}#vitrine">Retour aux services ↗</a></div>
<header class="header"><a class="brand" href="{{ route('demo.vitrine') }}">atelier rive<span>ARCHITECTURE & INTÉRIEURS</span></a><button class="menu-toggle" type="button" aria-controls="navigation" aria-expanded="false" hidden>Menu</button><nav id="navigation" aria-label="Navigation principale">@foreach($pages as $slug => $label)<a href="{{ route('demo.vitrine', ['page' => $slug]) }}" @if($page === $slug) aria-current="page" @endif>{{ $label }}</a>@endforeach</nav></header>
<main id="main">
@if($page === 'accueil')
<section class="hero wrap"><div class="hero-copy"><p class="eyebrow">Des lieux à vivre, naturellement.</p><h1>L’espace juste.<br><em>La vie autour.</em></h1><p class="lead">Imaginer des intérieurs qui respirent. Révéler la lumière, respecter les matières et faire de chaque lieu une évidence.</p><a class="button" href="{{ route('demo.vitrine', ['page'=>'realisations']) }}">Explorer nos réalisations <span class="mobile-decoration" aria-hidden="true">↗</span></a><p class="hero-foot">Architecture intérieure · Rénovation · Aménagement</p></div><figure class="hero-image"><img src="{{ asset('images/atelier/interieur.jpg') }}" alt="Salon lumineux aux matières naturelles" width="1400" height="934" fetchpriority="high"><figcaption>01 / Maison Lumière — Projet de concept</figcaption></figure></section>
<section class="wrap intro section"><p class="eyebrow">Une vision sensible de l’habitat</p><div><h2>Un lieu se dessine.<br><em>Un équilibre se ressent.</em></h2><p>Nous imaginons l’architecture à partir de ceux qui l’habitent. Les usages donnent le rythme, la lumière trace les lignes, les matières installent la douceur.</p><a class="text-link" href="{{ route('demo.vitrine', ['page'=>'atelier']) }}">Rencontrer l’univers de l’atelier <span class="mobile-decoration" aria-hidden="true">↗</span></a></div></section>
<section class="wrap section"><div class="section-head"><h2>Fragments <em>de lieux.</em></h2><a class="text-link" href="{{ route('demo.vitrine', ['page'=>'realisations']) }}">Tous les projets <span class="mobile-decoration" aria-hidden="true">↗</span></a></div><div class="projects">@foreach(array_slice($projects,0,2) as $project)<a class="project" href="{{ route('demo.vitrine', ['page'=>'realisations']) }}#projet-{{ $loop->index }}"><img src="{{ asset('images/atelier/'.$project[2]) }}" alt="{{ $project[0] }}, inspiration d’intérieur" loading="lazy" width="1000" height="750"><div><span class="eyebrow">{{ $project[1] }}</span><h3>{{ $project[0] }} <span><span class="mobile-decoration" aria-hidden="true">↗</span></span></h3><p>{{ $project[3] }}</p></div></a>@endforeach</div></section>
@elseif($page === 'atelier')
<section class="wrap page-title"><p class="eyebrow">L’atelier / Notre regard</p><h1>Habiter autrement.<br><em>Commencer par vous.</em></h1><p class="lead">Un atelier imaginé autour de l’écoute, de la simplicité et du plaisir de vivre dans un espace qui nous ressemble.</p></section><section class="wrap editorial section"><img src="{{ asset('images/atelier/matiere.jpg') }}" alt="Intérieur aux matières et tons naturels" width="1000" height="750"><div><p class="eyebrow">Notre philosophie</p><h2>Moins de superflu.<br><em>Plus de sens.</em></h2><p>Avant les plans viennent les conversations. Comment un lieu est-il vécu ? Qu’aimerait-on y changer ? Quels détails méritent d’être conservés ?</p><p>Cette approche privilégie des espaces lisibles, des matières expressives et des choix cohérents. Le projet se construit dans le dialogue, du premier croquis aux derniers détails.</p></div></section><section class="wrap section pillars"><article><span>01 / ÉCOUTER</span><h3>Comprendre les usages.</h3><p>Mettre les habitudes et les envies au cœur de la réflexion.</p></article><article><span>02 / RÉVÉLER</span><h3>Respecter l’existant.</h3><p>Identifier ce qui fait le caractère du lieu et lui donner sa place.</p></article><article><span>03 / ÉQUILIBRER</span><h3>Dessiner l’essentiel.</h3><p>Relier fonctionnalité, lumière et cohérence des matières.</p></article></section>
@elseif($page === 'expertises')
<section class="wrap page-title"><p class="eyebrow">Expertises / Du regard au détail</p><h1>Chaque projet,<br><em>sa juste réponse.</em></h1><p class="lead">Une approche à différentes échelles, de la transformation d’un lieu à l’aménagement de ses espaces.</p></section><section class="wrap section services">@foreach([['Architecture intérieure','Repenser les volumes, les perspectives et les circulations pour faire émerger un espace harmonieux.','Organisation des espaces · Ambiances · Choix des matières'],['Rénovation','Révéler les qualités d’un lieu existant, conserver ses singularités et l’adapter à de nouveaux usages.','Lecture de l’existant · Intentions de transformation · Cohérence du projet'],['Aménagement','Composer un intérieur dans lequel chaque élément trouve sa place, du mobilier à la lumière.','Mobilier · Couleurs · Éclairage · Détails']] as $service)<article><span class="eyebrow">0{{ $loop->iteration }}</span><div><h2>{{ $service[0] }}</h2><p>{{ $service[1] }}</p><small>{{ $service[2] }}</small></div></article>@endforeach</section><section class="wrap process section"><p class="eyebrow">Le parcours d’un projet</p><h2>De l’idée <em>au lieu.</em></h2><div class="pillars"><article><h3>01. La rencontre</h3><p>Explorer le contexte, les usages et les aspirations.</p></article><article><h3>02. La conception</h3><p>Donner forme aux idées avec des plans et des intentions de matières.</p></article><article><h3>03. Les détails</h3><p>Affiner les choix pour un ensemble cohérent.</p></article></div></section>
@elseif($page === 'realisations')
<section class="wrap page-title"><p class="eyebrow">Réalisations / Carnet d’inspirations</p><h1>Des espaces.<br><em>Des façons de vivre.</em></h1><p class="lead">Trois projets de concept pour explorer notre univers. Les photographies sont des illustrations d’ambiance, pas des réalisations d’une agence réelle.</p></section><section class="wrap section"><div class="filters" role="group" aria-label="Filtrer les projets">@foreach(['Tous','Habitat','Rénovation','Aménagement'] as $filter)<button type="button" data-filter="{{ $filter }}" aria-pressed="{{ $loop->first ? 'true' : 'false' }}">{{ $filter }}</button>@endforeach</div><div class="projects">@foreach($projects as $project)<article class="project" id="projet-{{ $loop->index }}" data-category="{{ $project[1] }}"><img src="{{ asset('images/atelier/'.$project[2]) }}" alt="{{ $project[0] }}, illustration d’ambiance" width="1000" height="750" loading="lazy"><div><span class="eyebrow">{{ $project[1] }} · Concept 0{{ $loop->iteration }}</span><h2>{{ $project[0] }}</h2><p>{{ $project[3] }}</p><details><summary>Découvrir l’intention du projet</summary><p>Un travail sur la continuité des espaces, les contrastes de textures et la place de la lumière naturelle. Une inspiration pour des intérieurs simples, chaleureux et agréables à vivre.</p></details></div></article>@endforeach</div><p class="filter-status" role="status" aria-live="polite"></p></section>
@else
<section class="wrap page-title"><p class="eyebrow">Contact / Premier échange</p><h1>Tout commence<br><em>par une conversation.</em></h1><p class="lead">Présenter un projet, partager une envie, poser une question. Voici un exemple de formulaire de prise de contact.</p></section><section class="wrap contact-grid section"><div><h2>Parlons <em>de votre lieu.</em></h2><p>La première rencontre permet de préciser vos besoins et de comprendre ce qui compte pour vous.</p><div class="contact-note"><span class="eyebrow">Démonstration</span><p>Atelier Rive est une marque fictive. Ce formulaire illustre l’expérience de contact : aucune information n’est envoyée ni enregistrée.</p></div><a class="text-link" href="{{ route('contact') }}">Contacter réellement Codenyr <span class="mobile-decoration" aria-hidden="true">↗</span></a></div><form id="demo-contact"><label for="name">Votre nom</label><input id="name" name="name" autocomplete="name" required maxlength="100"><label for="email">Votre adresse e-mail</label><input id="email" name="email" type="email" autocomplete="email" required maxlength="200"><label for="project-type">Votre projet</label><select id="project-type" name="project"><option>Architecture intérieure</option><option>Rénovation</option><option>Aménagement</option></select><label for="message">Quelques mots sur votre projet</label><textarea id="message" name="message" rows="4" required maxlength="3000"></textarea><button class="button" type="submit" disabled>Tester le formulaire <span class="mobile-decoration" aria-hidden="true">↗</span></button><noscript>Activez JavaScript pour essayer le formulaire.</noscript><p id="form-result" role="status" aria-live="polite"></p></form></section>
@endif
@if($page !== 'contact')<section class="wrap invitation"><p class="eyebrow">Une nouvelle perspective</p><h2>Et si l’on imaginait<br><em>la suite ensemble ?</em></h2><a class="button" href="{{ route('demo.vitrine', ['page'=>'contact']) }}">Faire le premier pas <span class="mobile-decoration" aria-hidden="true">↗</span></a></section>@endif
</main><footer class="wrap"><div class="footer-top"><a class="brand" href="{{ route('demo.vitrine') }}">atelier rive<span>DES LIEUX QUI ONT DU SENS.</span></a><p>Architecture intérieure & lieux de vie.<br>Un site vitrine imaginé par Codenyr.</p></div><div class="footer-bottom"><span>Marque et projets fictifs · Photos d’ambiance Unsplash</span><a href="{{ route('services') }}#vitrine">Retour à Codenyr ↗</a></div></footer>
<button id="studio-toggle" class="studio-toggle" type="button" aria-controls="studio" aria-expanded="false" hidden>Plus de possibilités <span aria-hidden="true">+</span></button><section id="studio" class="studio" aria-labelledby="studio-title" hidden><div class="studio-head"><div><span>LE STUDIO CODENYR</span><h2 id="studio-title">Imaginez votre version.</h2></div><button type="button" id="studio-close" aria-label="Fermer les possibilités">×</button></div><p>10 réglages combinables. Votre choix vous suit d’une page à l’autre dans cet onglet.</p><form id="studio-form">@foreach($settings as $key => [$label, $options])<label for="setting-{{ $key }}">{{ $label }}</label><select id="setting-{{ $key }}" name="{{ $key }}">@foreach($options as $value => $name)<option value="{{ $value }}">{{ $name }}</option>@endforeach</select>@endforeach<button type="reset">Revenir au design initial</button></form><p class="studio-status" role="status" aria-live="polite"></p></section></body></html>
