@php
    $pages = ['accueil'=>'Accueil', 'studio'=>'Le studio', 'realisations'=>'Réalisations', 'journal'=>'Journal', 'gestion'=>'Gestion démo'];
    $settings = ['palette' => ['Palette', ['mineral' => 'Lin & feuillage', 'olive' => 'Olive & lin', 'blue' => 'Bleu architectural', 'rose' => 'Rose poudré', 'dark' => 'Obsidienne']], 'type' => ['Typographie', ['signature' => 'Signature éditoriale', 'modern' => 'Contemporaine', 'classic' => 'Classique']], 'layout' => ['Présentation d’accueil', ['split' => 'Composition en deux colonnes', 'reverse' => 'Image à gauche', 'wide' => 'Panorama']], 'nav' => ['Navigation', ['standard' => 'Horizontale', 'center' => 'Centrée', 'sticky' => 'Fixe au défilement']], 'cards' => ['Présentation des projets', ['grid' => 'Grille', 'list' => 'Liste éditoriale']], 'corners' => ['Formes', ['square' => 'Angles droits', 'rounded' => 'Arrondis']], 'density' => ['Espacement', ['airy' => 'Généreux', 'compact' => 'Compact']], 'width' => ['Largeur du contenu', ['large' => 'Large', 'narrow' => 'Resserrée']], 'photos' => ['Traitement des photos', ['natural' => 'Naturel', 'mono' => 'Noir et blanc', 'warm' => 'Chaleureux']], 'buttons' => ['Style des boutons', ['solid' => 'Pleins', 'outline' => 'Contours']]];
@endphp
<!DOCTYPE html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>{{ $pages[$page] }} — Canopée · Démonstration Codenyr</title>@fonts @vite('resources/js/demo-pro.js')</head><body data-preview-key="codenyr-canopee-preview-v1">
<a class="skip" href="#main">Aller au contenu</a>
<div class="demo-banner"><span>CANOPÉE · Concept fictif par Codenyr</span><a href="{{ route('services') }}#pro">Retour aux services <span class="mobile-decoration" aria-hidden="true">↗</span></a></div>
<header class="header"><a class="brand" href="{{ route('demo.pro') }}">canopée<span>STUDIO DE PAYSAGE</span></a><button class="menu-toggle" type="button" aria-controls="navigation" aria-expanded="false" hidden>Menu</button><nav id="navigation" aria-label="Navigation principale">@foreach($pages as $slug => $label)<a href="{{ route('demo.pro', ['page' => $slug]) }}" @if($page === $slug) aria-current="page" @endif>{{ $label }}</a>@endforeach</nav></header>

<main id="main">
@if($page === 'accueil')
<section class="hero wrap"><div class="hero-copy"><p class="eyebrow">Studio de paysage · Jardins vivants</p><h1>Faire place<br><em>au vivant.</em></h1><p class="lead">Des jardins qui suivent les saisons. Des espaces extérieurs pensés pour se retrouver, respirer et laisser la nature prendre sa place.</p><a class="button" href="{{ route('demo.pro', ['page'=>'realisations']) }}">Découvrir les jardins <span class="mobile-decoration" aria-hidden="true">↗</span></a><p class="hero-foot">Conception paysagère · Terrasses · Jardins de ville</p></div><figure class="hero-image"><img src="{{ asset('images/canopee/jardin.jpg') }}" alt="Outils de jardinage et terreau sur une table" width="1400" height="1000" fetchpriority="high"><figcaption>Le paysage comme espace de vie.</figcaption></figure></section>
<section class="wrap intro section"><p class="eyebrow">Un site qui vit avec vous</p><div><h2>De nouvelles idées.<br><em>Au fil des saisons.</em></h2><p>Ce site de démonstration dispose de deux collections administrables : les réalisations et les articles du journal. Explorez la gestion, publiez un contenu et retrouvez-le immédiatement sur les pages publiques.</p><a class="text-link" href="{{ route('demo.pro', ['page'=>'gestion']) }}">Essayer la gestion des contenus <span class="mobile-decoration" aria-hidden="true">↗</span></a></div></section>
<section class="wrap section"><div class="section-head"><h2>Les derniers <em>jardins.</em></h2><a class="text-link" href="{{ route('demo.pro', ['page'=>'realisations']) }}">Toutes les réalisations <span class="mobile-decoration" aria-hidden="true">↗</span></a></div><div class="projects" data-collection="projects" data-limit="2"></div></section>
@elseif($page === 'studio')
<section class="wrap page-title"><p class="eyebrow">Le studio / Notre approche</p><h1>Penser les lieux.<br><em>Respecter leur nature.</em></h1><p class="lead">Canopée est un studio fictif imaginé autour d’une conviction : un jardin se conçoit autant pour ce qu’il est aujourd’hui que pour ce qu’il deviendra.</p></section><section class="wrap editorial section"><img src="{{ asset('images/canopee/jardin.jpg') }}" alt="Terreau et outils pour préparer des plantations" width="1400" height="1000"><div><h2>Observer avant<br><em>de dessiner.</em></h2><p>Les usages, la lumière et les changements de saison donnent le point de départ. Le dessin relie ensuite les espaces, ménage les perspectives et compose avec le végétal.</p><p>Du petit extérieur urbain au jardin familial, chaque projet cherche un équilibre entre lieux de vie, matières naturelles et plantations.</p></div></section><section class="wrap section pillars"><article><span>01 / CONCEVOIR</span><h3>Un plan d’ensemble.</h3><p>Relier les circulations, les usages et les différentes ambiances.</p></article><article><span>02 / COMPOSER</span><h3>Une palette vivante.</h3><p>Associer les textures, les volumes et les couleurs au fil des saisons.</p></article><article><span>03 / ACCOMPAGNER</span><h3>Un lieu qui évolue.</h3><p>Imaginer la place de chaque espace dans le quotidien de ses habitants.</p></article></section>
@elseif($page === 'realisations' || $page === 'journal')
<section class="wrap page-title"><p class="eyebrow">{{ $page === 'journal' ? 'Journal / Regards sur le paysage' : 'Réalisations / Inspirations paysagères' }}</p><h1>{{ $page === 'journal' ? 'Les idées prennent' : 'Des jardins pour' }}<br><em>{{ $page === 'journal' ? 'racine ici.' : 'les jours heureux.' }}</em></h1><p class="lead">{{ $page === 'journal' ? 'Conseils, inspirations et nouvelles du studio. Une collection que vous pouvez enrichir depuis la gestion de démonstration.' : 'Une sélection de projets fictifs, illustrés par des photographies d’ambiance. Découvrez leurs intentions ou ajoutez votre propre exemple.' }}</p></section><section class="wrap section"><label class="search-label" for="collection-search">Rechercher {{ $page === 'journal' ? 'un article' : 'une réalisation' }}</label><input class="collection-search" id="collection-search" type="search" placeholder="Un titre, une catégorie…"><div class="projects" data-collection="{{ $page === 'journal' ? 'articles' : 'projects' }}"></div><p class="collection-status" role="status"></p></section>
@else
<section class="wrap page-title"><p class="eyebrow">Administration de démonstration</p><h1>Votre site.<br><em>Vos contenus.</em></h1><p class="lead">Deux modules à essayer : réalisations et actualités. Vos modifications restent dans ce navigateur et ne changent pas le site des autres visiteurs. Aucun compte nécessaire pour cette simulation.</p></section><section class="wrap section manager"><div class="manager-toolbar"><div class="filters" role="group" aria-label="Collection à gérer"><button type="button" data-module="projects" aria-pressed="true">Réalisations</button><button type="button" data-module="articles" aria-pressed="false">Actualités</button></div><button class="button" id="new-entry" type="button">Ajouter un contenu +</button></div><p class="manager-feedback" role="status" aria-live="polite"></p><div id="manager-list"></div><button class="text-link reset-content" id="reset-content" type="button">Restaurer les contenus de démonstration</button><p class="storage-note">Les brouillons sont visibles ici uniquement. Les contenus publiés apparaissent sur les pages du site.</p></section>
<dialog id="editor" aria-labelledby="editor-title"><form id="entry-form"><div class="editor-head"><h2 id="editor-title">Ajouter un contenu</h2><button type="button" id="close-editor" aria-label="Fermer l’éditeur">×</button></div><input type="hidden" id="entry-id"><label for="entry-title">Titre</label><input id="entry-title" required maxlength="100"><label for="entry-category">Catégorie</label><input id="entry-category" required maxlength="50"><label for="entry-text">Présentation</label><textarea id="entry-text" rows="5" required maxlength="2000"></textarea><label for="entry-image">Photographie d’ambiance</label><select id="entry-image"><option value="garden">Jardin</option><option value="interior">Espace de vie</option><option value="material">Matières naturelles</option></select><label for="entry-state">Visibilité</label><select id="entry-state"><option value="published">Publié</option><option value="draft">Brouillon</option></select><button class="button" type="submit">Enregistrer</button></form></dialog>
@endif
<noscript><p class="wrap section">Activez JavaScript pour découvrir les collections interactives et la gestion de démonstration.</p></noscript>
</main><footer class="wrap"><div class="footer-top"><a class="brand" href="{{ route('demo.pro') }}">canopée<span>DES LIEUX QUI ONT DU SENS.</span></a><p>Paysage & jardins vivants.<br>Un site pro imaginé par Codenyr.</p></div><div class="footer-bottom"><span>Marque et projets fictifs · Photos d’ambiance Unsplash</span><a href="{{ route('services') }}#pro">Retour à Codenyr <span class="mobile-decoration" aria-hidden="true">↗</span></a></div></footer>
<button id="studio-toggle" class="studio-toggle" type="button" aria-controls="studio" aria-expanded="false" hidden>Plus de possibilités <span aria-hidden="true">+</span></button><section id="studio" class="studio" aria-labelledby="studio-title" hidden><div class="studio-head"><div><span>LE STUDIO CODENYR</span><h2 id="studio-title">Imaginez votre version.</h2></div><button type="button" id="studio-close" aria-label="Fermer les possibilités">×</button></div><p>10 réglages combinables. Votre choix vous suit d’une page à l’autre dans cet onglet.</p><form id="studio-form">@foreach($settings as $key => [$label, $options])<label for="setting-{{ $key }}">{{ $label }}</label><select id="setting-{{ $key }}" name="{{ $key }}">@foreach($options as $value => $name)<option value="{{ $value }}">{{ $name }}</option>@endforeach</select>@endforeach<button type="reset">Revenir au design initial</button></form><p class="studio-status" role="status" aria-live="polite"></p></section></body></html>
