<h2>Comptes clients et avis</h2>
<p>L’inscription collecte votre nom, votre e-mail et votre mot de passe stocké sous forme hachée. @if(\Laravel\Fortify\Features::enabled(\Laravel\Fortify\Features::emailVerification())) L’adresse e-mail doit être vérifiée. @endif Codenyr associe explicitement le compte à un projet ; seuls les projets dont le devis est accepté et le site livré donnent accès au dépôt d’un avis.</p>
<p>Avec votre accord, votre nom, votre entreprise, votre note et votre avis pourront être affichés publiquement après validation par Codenyr. Votre e-mail et les retours de modération ne sont pas publiés. Toute modification de l’avis nécessite une nouvelle validation. Vous pouvez retirer votre accord directement dans « Mes données personnelles » ou contacter Codenyr. La date et la version de l’accord sont enregistrées lors des nouvelles soumissions ; le retrait masque immédiatement l’avis. La suppression du compte entraîne également la suppression des avis qui lui sont associés.</p>

<h2>Dossiers et documents commerciaux</h2>
<p>Les fiches clients, dossiers, devis, factures, règlements et documents de prestation servent à préparer et exécuter le contrat, suivre les paiements et respecter les obligations comptables. Ils peuvent contenir les coordonnées de facturation, le détail des prestations, les dates, les montants et les pièces signées. Les références de règlement sont saisies par Codenyr ; cet espace ne recueille pas vos numéros de carte bancaire.</p>
<p>Votre accès dépend d’un rattachement explicite du compte au dossier. Seuls les fichiers partagés par Codenyr sont téléchargeables après connexion. Les notes internes et les brouillons restent réservés à l’administration. Changer de compte ou de client retire les partages jusqu’à une nouvelle décision de Codenyr. Les fichiers sont stockés dans un espace privé et les droits sont contrôlés à chaque téléchargement.</p>
<p>Les factures et justificatifs comptables sont conservés pendant dix ans à compter de la clôture de l’exercice concerné. La suppression du compte retire l’accès et supprime ses avis, mais ne supprime pas automatiquement les données contractuelles et comptables que Codenyr doit conserver.</p>
<p>Dans « Mes données personnelles », vous pouvez enregistrer une demande d’accès, de rectification, d’effacement, de limitation, d’opposition ou de portabilité et consulter la réponse. Votre e-mail, le type de demande, vos précisions et les dates de traitement sont conservés pour traiter et justifier la réponse. L’effacement dépend du traitement et de ses obligations de conservation ; la clôture d’une demande ne déclenche pas une suppression automatique.</p>
<p>Le délai initial de réponse est d’un mois. Une prolongation justifiée, lorsqu’elle est nécessaire en raison de la complexité ou du nombre des demandes, vous est expliquée dans ce délai. Sans compte, vous pouvez exercer les mêmes droits par e-mail.</p>
