<x-site-layout title="Politique de confidentialité" description="Données personnelles, cookies et droits : découvrez comment Codenyr traite les informations de vos demandes et de votre compte client.">
<section class="container page-hero"><p class="eyebrow">Vos données</p><h1>Politique de confidentialité.</h1><p>Dernière mise à jour : 1er octobre 2026.</p></section>
<section class="container section prose legal-prose">
<h2>Responsable et contact</h2><p>Codenyr traite les informations nécessaires aux échanges et au suivi des projets. Pour toute question concernant vos données, écrivez à <a href="mailto:{{ config('codenyr.email') }}">{{ config('codenyr.email') }}</a>. L’identité légale de l’éditeur figure dans les <a href="{{ route('legal') }}">mentions légales</a>.</p>
<h2>Données collectées et utilisation</h2><p>Les formulaires recueillent votre prénom, votre nom, votre e-mail et votre demande. Selon le formulaire, vous pouvez aussi indiquer votre entreprise, votre téléphone, votre site et le délai souhaité. Les champs obligatoires sont signalés par un astérisque. Ces informations servent à vous répondre, préparer un devis et suivre les échanges. Une demande de devis relève des mesures précontractuelles demandées par vous ; les échanges généraux et la protection du service relèvent de l’intérêt légitime à répondre aux demandes et à sécuriser le site.</p>
<p>Les comptes clients servent au suivi des projets associés. Les informations contractuelles nécessaires à une prestation sont traitées pour son exécution et, lorsqu’elles s’appliquent, pour satisfaire aux obligations légales. La publication d’un avis client nécessite votre accord.</p>
<h2>Destinataires et prestataires</h2><p>Les données sont accessibles aux personnes autorisées de Codenyr et aux prestataires techniques nécessaires à l’hébergement et à l’envoi des e-mails. Elles ne sont pas vendues et aucun service publicitaire n’est intégré au site.</p>
<div class="notice"><strong>Informations de production à compléter</strong><p>L’identité et l’adresse légales de l’éditeur, les prestataires d’hébergement et d’e-mail, leur localisation et les éventuels transferts hors de l’Espace économique européen doivent être précisés avant l’ouverture publique du service. Ces informations ne sont pas encore renseignées.</p></div>
<h2>Conservation</h2><p>Les demandes et échanges sont conservés pendant la durée nécessaire à leur traitement et au suivi du projet. Les comptes restent enregistrés jusqu’à leur suppression ; certaines pièces relatives à une prestation peuvent être conservées séparément pour les obligations légales et la défense des droits. La simple clôture ou l’archivage d’un projet ne supprime pas ses données. Les durées exactes et la procédure de purge doivent être définies par l’éditeur avant l’ouverture publique.</p>
@include('site.customer-privacy')
<h2>Sécurité des formulaires</h2><p>Les formulaires sont validés côté serveur et protégés contre les soumissions automatisées par un champ de détection et une limitation temporaire des tentatives, fondée sur l’adresse IP. Les mots de passe sont hachés ; les accès administrateur sont restreints. Les connexions sont chiffrées par HTTPS.</p>
<h2>Cookies et stockage du navigateur</h2><p>Les cookies de session, d’authentification et de protection des formulaires sont nécessaires au service. Aucun outil publicitaire ni mesure d’audience tiers n’est installé actuellement. Votre choix concernant les cookies facultatifs est conservé dans le navigateur pendant 180 jours et peut être changé via « Gérer les cookies » dans le pied de page. Accepter n’active aucun traceur absent du site ; refuser n’empêche pas l’accès aux services.</p>
<p>Les démonstrations utilisent également le stockage local pour conserver les réglages et les contenus fictifs que vous essayez. Elles ne doivent pas recevoir de données personnelles réelles. Les données de démonstration peuvent être effacées depuis les réglages de stockage du navigateur.</p>
<h2>Vos droits</h2><p>Selon le traitement concerné, vous pouvez demander l’accès, la rectification, l’effacement, la limitation, la portabilité ou vous opposer au traitement. Vous pouvez retirer votre accord à la publication d’un avis sans remettre en cause la licéité de sa publication antérieure. Contactez {{ config('codenyr.email') }} ; une vérification d’identité proportionnée peut être nécessaire en cas de doute.</p>
<p>Vous pouvez également introduire une réclamation auprès de la <a href="https://www.cnil.fr/fr/plaintes" rel="noopener noreferrer">CNIL</a>.</p>
</section></x-site-layout>
