<x-site-layout title="Conditions générales d’utilisation" description="Les conditions d’accès et d’utilisation du site Codenyr, des comptes clients et des démonstrations.">
<section class="container page-hero"><p class="eyebrow">Utilisation du site</p><h1>Conditions générales d’utilisation.</h1><p>Dernière mise à jour : 1er octobre 2026.</p></section>
<section class="container section prose legal-prose">
<h2>Objet et accès</h2><p>Ces conditions précisent les règles d’utilisation du site Codenyr, qui présente des prestations de développement web, des réalisations et des démonstrations. La consultation est gratuite, hors frais de connexion de votre opérateur. L’identité de l’éditeur est précisée dans les <a href="{{ route('legal') }}">mentions légales</a>.</p>
<h2>Demandes et prestations</h2><p>Un formulaire de contact ou de devis permet d’engager un échange sans obligation d’achat. Les prix affichés sont des points de départ. Le périmètre, le prix définitif, les délais et les engagements d’une prestation sont définis dans un devis et les documents contractuels correspondants. Les présentes CGU ne remplacent pas ces documents.</p>
<h2>Comptes clients</h2><p>Vous devez fournir des informations exactes et protéger vos identifiants. Un compte client donne accès aux fonctionnalités autorisées pour les projets associés par Codenyr. Il ne donne aucun droit d’administration. Signalez toute utilisation non autorisée à {{ config('codenyr.email') }}.</p>
<h2>Avis et contenus transmis</h2><p>Vous êtes responsable des informations et contenus que vous transmettez. N’envoyez aucun contenu illicite, diffamatoire, trompeur, ni aucune donnée ou œuvre que vous n’êtes pas autorisé à communiquer. Les avis sont publiés avec votre accord après modération ; toute modification nécessite une nouvelle validation.</p>
<h2>Démonstrations</h2><p>Les marques, clients, projets et identifiants présentés dans les démonstrations sont fictifs. Les simulations n’émettent aucun devis, paiement ou réservation réel. Leurs réglages et contenus peuvent être conservés dans le navigateur utilisé. Évitez d’y saisir des données personnelles réelles.</p>
<h2>Propriété intellectuelle</h2><p>Les textes, visuels, logos et développements du site sont protégés selon les droits applicables. Leur réutilisation nécessite l’autorisation du titulaire concerné, sauf exception prévue par la loi. Les droits sur les images et contenus de tiers restent ceux de leurs titulaires.</p>
<h2>Usage raisonnable et disponibilité</h2><p>Il est interdit de tenter de compromettre le site, d’accéder sans autorisation aux données ou comptes, ou de perturber le service. Codenyr peut interrompre l’accès pour maintenance ou pour traiter un abus. Malgré le soin apporté aux contenus, des erreurs ou interruptions peuvent survenir ; vous pouvez les signaler à l’adresse de contact.</p>
<h2>Données personnelles et cookies</h2><p>Consultez la <a href="{{ route('privacy') }}">politique de confidentialité</a> pour connaître les traitements de données et les cookies utilisés. Le lien « Gérer les cookies » reste disponible dans le pied de page.</p>
<h2>Évolution et contact</h2><p>Ces conditions peuvent évoluer avec les fonctionnalités du site. La version publiée indique sa date de mise à jour. Pour toute question, écrivez à <a href="mailto:{{ config('codenyr.email') }}">{{ config('codenyr.email') }}</a>. Les droits impératifs applicables aux utilisateurs restent préservés.</p>
</section></x-site-layout>
