<!DOCTYPE html><html lang="fr"><head><meta charset="utf-8"><style>
@page { margin: 32px; } body { font-family: DejaVu Sans, sans-serif; font-size: 10px; color: #182430; } h1 { font-size: 25px; } h2 { font-size: 14px; margin-top: 22px; } .brand { width: 150px; } .muted { color: #546472; } table { width: 100%; border-collapse: collapse; margin-top: 15px; } th { background: #edf2f4; text-align: left; } td, th { padding: 8px; border-bottom: 1px solid #dce4e8; } .amount { text-align: right; white-space: nowrap; } .description { font-size: 9px; color: #546472; } .total { font-size: 14px; font-weight: bold; } .lines { white-space: pre-wrap; } .draft { padding: 10px; background: #fff1d6; } tr { page-break-inside: avoid; }
</style></head><body>
<img class="brand" src="{{ !empty($record->snapshot['seller']['logo_path']) ? \Illuminate\Support\Facades\Storage::disk('local')->path($record->snapshot['seller']['logo_path']) : public_path('images/codenyr.png') }}" alt="Codenyr">
@unless($record->finalized_at)<p class="draft">BROUILLON — {{ $kind==='invoice' ? 'Facture non émise' : 'Devis non envoyé' }}</p>@endunless
<h1>{{ $kind==='quote' ? 'Devis' : 'Facture' }} {{ $record->number ?? 'Brouillon #'.$record->id }}</h1>
@php($seller=$record->snapshot['seller']) @php($client=$record->snapshot['client'])
<table><tr><td><strong>{{ $seller['legal_name'] ?: $seller['name'] }}</strong><p class="lines">{{ $seller['address'] }}</p>{{ $seller['email'] }} · {{ $seller['phone'] }}<br>Identifiant : {{ $seller['registration'] }}</td><td><strong>{{ $client['name'] }}</strong><br>{{ $client['contact'] }}<p class="lines">{{ $client['address'] }}</p>{{ $client['email'] }}<br>{{ $client['phone'] }}<br>{{ $client['registration'] }}</td></tr></table>
<p><strong>Projet :</strong> {{ $record->snapshot['project']['name'] }}</p><p>Date : {{ $record->issued_on->format('d/m/Y') }} · {{ $kind==='quote' ? 'Valable jusqu’au' : 'Échéance' }} {{ $record->due_on->format('d/m/Y') }}</p>
@if($record instanceof \App\Models\Invoice)<p>Type : {{ \App\Models\Invoice::TYPES[$record->invoice_type] }}</p>@endif
@foreach(\App\Models\Service::FREQUENCIES as $frequency=>$label)
@php($lines=array_filter($record->items,fn($item)=>$item['frequency']===$frequency && (!$item['optional'] || $item['selected'])))
@if(count($lines))<h2>{{ $frequency==='once' ? ($kind==='invoice' ? 'Prestations facturées' : 'Prestations initiales') : 'Prestations récurrentes — '.$label }}</h2><table><thead><tr><th>Prestation</th><th>Qté</th><th>PU HT</th><th>Remise</th><th>TVA</th></tr></thead><tbody>@foreach($lines as $line)<tr><td><strong>{{ $line['name'] }}</strong><div class="description lines">{{ $line['description'] }}</div>@if(!empty($line['period_start']) && !empty($line['period_end']))<div class="description">Période facturée : du {{ \Carbon\Carbon::parse($line['period_start'])->format('d/m/Y') }} au {{ \Carbon\Carbon::parse($line['period_end'])->format('d/m/Y') }}</div>@endif</td><td>{{ rtrim(rtrim(\App\Services\CommercialCalculator::input($line['quantity_units']), '0'), '.') }}@if($line['unit'] !== 'forfait') {{ $line['unit'] }}@endif</td><td class="amount">{{ \App\Services\CommercialCalculator::euros($line['price_cents']) }}</td><td>{{ $line['discount_type']==='percent' ? \App\Services\CommercialCalculator::input($line['discount_value']).' %' : \App\Services\CommercialCalculator::euros($line['discount_value']) }}</td><td>{{ \App\Services\CommercialCalculator::input($line['vat_basis']) }} %</td></tr>@endforeach</tbody></table>
@php($total=$frequency==='once' ? $record->totals['initial'] : $record->totals['recurring'][$frequency])<table><tr><td>Sous-total HT</td><td class="amount">{{ \App\Services\CommercialCalculator::euros($total['subtotal']) }}</td></tr><tr><td>Remises</td><td class="amount">{{ \App\Services\CommercialCalculator::euros($total['discount']) }}</td></tr><tr><td>Total HT</td><td class="amount">{{ \App\Services\CommercialCalculator::euros($total['ht']) }}</td></tr><tr><td>TVA</td><td class="amount">{{ \App\Services\CommercialCalculator::euros($total['vat']) }}</td></tr><tr class="total"><td>{{ $frequency==='once' ? ($kind==='invoice' ? 'Total TTC à régler' : 'Total initial TTC') : 'Total TTC / '.$label }}</td><td class="amount">{{ \App\Services\CommercialCalculator::euros($total['ttc']) }}</td></tr></table>@endif
@endforeach
@if($kind==='quote')<p>Acompte initial : <strong>{{ \App\Services\CommercialCalculator::euros($record->totals['deposit']) }}</strong> · Solde prévisionnel : {{ \App\Services\CommercialCalculator::euros($record->totals['remaining']) }}</p>@endif
@php($options=array_filter($record->items,fn($item)=>$item['optional'] && !$item['selected']))
@if(count($options))<h2>Options non retenues — hors total</h2>@foreach($options as $option)<p>{{ $option['name'] }} · {{ \App\Services\CommercialCalculator::euros($option['price_cents']) }} HT / {{ $option['unit'] }} · {{ \App\Models\Service::FREQUENCIES[$option['frequency']] }}</p>@endforeach @endif
<p class="lines">{{ $seller['tax_mention'] }}</p><h2>Conditions</h2><p class="lines">{{ $record->conditions }}</p>@if($record->estimated_delay)<p>Délai estimé : {{ $record->estimated_delay }}</p>@endif
@if($kind==='quote')<h2>Acceptation</h2>@if(($record->totals['deposit'] ?? 0) > 0)<p>En signant ce devis, le client accepte de verser l’acompte de <strong>{{ \App\Services\CommercialCalculator::euros($record->totals['deposit']) }}</strong> avant le démarrage du projet. Le projet commencera après réception de cet acompte.</p>@endif<p>Nom, date, signature et mention « Bon pour accord » :</p><p>________________________________________________________________</p>@endif
<p class="muted lines">{{ $seller['footer'] }}</p></body></html>

